ebean:
  ddl:
    generate: true
    run: true
booking:
  app:
    jwtExpirationMs: 86400000
datasource:
  db:
    username: root
    password: "root"
    url: jdbc:mysql://localhost:3306/booking
    driver-class-name: com.mysql.cj.jdbc.Driver
  properties:
    jmxEnabled: true
    initialSize: 10
    maxActive: 50
    minIdle: 5
    maxIdle: 25
    maxWait: 10000
    maxAge: 600000
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 60000
    validationQueryTimeout: 3
    validationInterval: 15000
    validationQuery: "SELECT 1"
    dbProperties:
      autoReconnect: true
      # timeouts for TCP/IP
      connectTimeout: 15000
      socketTimeout: 120000

